"""
Django settings for lab1 project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

#settings.py - это файл, в котором хранятся настройки проекта, базы данных, установленные приложения, middleware и статические файлы

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.

# Разрешенные хосты
ALLOWED_HOSTS = ['*']  # В продакшене замените на реальные домены

#В BASE_DIR записан путь к корню проекта
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECRET_KEY = 'django-insecure-^f5q$nc=&-afw+#68z++k3ysy=7%l%h&3d-%5^)j+s2b4sffo='
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-^f5q$nc=&-afw+#68z++k3ysy=7%l%h&3d-%5^)j+s2b4sffo=')

# SECURITY WARNING: don't run with debug turned on in production!

#Если появляется ошибка, она сразу же отображается на экране.
DEBUG = True




# Application definition

#Список всех подключенных приложений, включает в себя встроенные и вами созданные приложения
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'mainapp', # Моё основное приложение
]

#Middleware - набор обработчиков, которые обрабатывают каждый HTTP-запрос и ответ. Примечание: стоят посередние между клиентом (браузером) и views.py
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#ROOT_URLCONF указывает на файл, в котором хранятся все маршруты в проекте 
# (здесь ROOT_URLCONF указывает на файл с путем в проекте: lab1/urls.py)
ROOT_URLCONF = 'lab1.urls'

#TEMPLATES отвечает за рендер HTML и подключение шаблонов, 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', #BACKEND обозначает, какой движок будет обрабатывать HTML-шаболны. В данном случае используется стандартный шаблонизатор Django
        'DIRS': [BASE_DIR / 'templates'], #DIRS - список папок, в которых лежат шаблоны.
        'APP_DIRS': True, #APP_DIRS - включает автоматический поиск шаблонов внутри приложений. В таком случае Django сам будет находить файлы.
        'OPTIONS': { #OPTIONS - это дополнительные настройки для шаблонизатора в Django
            'context_processors': [ #context_processors - это функции, которые автоматически добавляют данные в контекст всех шаблонов
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#Это точка входа, через которую сервер будет запускать данный проект.
WSGI_APPLICATION = 'lab1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#Базы данных

#Так как запускаем Django-проект в Docker, то и изменяем обращения в базах данных
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators


#AUTH_PASSWORD_VALIDATORS - это список валидаторов пароля. 
# Здесь каждый NAME - это валидатор пароля, который проверяет его на соответствие всем правилам. 
# Если хотя бы один валидатор выдаёт ошибку, то пароль отклоняется.
AUTH_PASSWORD_VALIDATORS = [
    { #Пароль не должен быть похож на данные пользователя
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    { #Минимальная длина пароля >= 8 символов
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    { #Запрещает использование простых паролей
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    { #Запрещает пароль, состоящий только из цифр
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

#Язык, на котором отображается весь текст проекта (язык админки, встроенные сообщения Django, формат дат/чисел)
LANGUAGE_CODE = 'en-us'

#Для использования нескольких языков используется 
# LANGUAGES = [
#     ('en', 'English'),
#     ('ru', 'Russian'),
#     ('de', 'German'),
# ]
# А также нужно подключить middleware: 'django.middleware.locale.LocaleMiddleware'
#Часовой пояс всех используемых дат и времени в проекте
TIME_ZONE = 'UTC' #Значение часового пояса в данном случае: "Европа/Вена"

#Включает поддержку нескольких и более языков. В данном случае если True, то Django переводит сайт на языки, указанные в LANGUAGE_CODE.
USE_I18N = True

# Куда Django соберет статические файлы (в Docker)
STATIC_ROOT = '/app/staticfiles'

#Включает поддержку нескольких часовых поясов. 
#В данном случае всё время для пользователя 
#будет отображаться в его часовом поясе, 
#но в системе оно будет сохранятся в виде UTC.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

#STATIC_URL - путь к папке, в которой хранятся все файлы, относящиеся к категории static (это, например, картинки, CSS-файлы, JS-файлы).
STATIC_URL = '/static/'